# Generated by Django 5.0 on 2023-12-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0002_comment_comment_user_comment_content_comment_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
