# Generated by Django 5.0 on 2023-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_post_native_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='native_lang',
            field=models.CharField(blank=True, default=''),
        ),
    ]
