# Generated by Django 5.0 on 2023-12-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_alter_post_native_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='native_lang',
        ),
    ]
