# Generated by Django 5.0 on 2023-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_post_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lang',
            field=models.CharField(blank=True, verbose_name='native_language'),
        ),
    ]
