# Generated by Django 5.0 on 2023-12-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_post_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lang',
        ),
    ]
