# Generated by Django 5.0 on 2023-12-07 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ko', 'Korean'), ('es', 'Spanish')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ko', 'Korean'), ('es', 'Spanish')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
    ]
