# Generated by Django 5.0 on 2023-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_display_name_user_native_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(choices=[('English', 'English'), ('Korean', 'Korean'), ('Spanish', 'Spanish')]),
        ),
    ]
