# Generated by Django 5.0 on 2023-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_language',
            field=models.CharField(blank=True, choices=[('en', 'en'), ('ko', 'ko'), ('es', 'es')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, choices=[('en', 'en'), ('ko', 'ko'), ('es', 'es')], null=True),
        ),
    ]
