# Generated by Django 5.0 on 2023-12-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_user_target_language_alter_user_native_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ko', 'ko'), ('es', 'es')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='target_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ko', 'ko'), ('es', 'es')], null=True),
        ),
    ]
